language: cpp
os: osx
before_install: brew update >/dev/null
env:
    global:
        - HOMEBREW_VERBOSE=1
    matrix:
        - PARAMS=--with-qt5
        - PARAMS=--without-qt5
install:
    - brew options dspdfviewer.rb
    - brew install dspdfviewer.rb $PARAMS
script: dspdfviewer --version
